name: CI-develop

on:
  push:
    branches:
      - deploy-git-action

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '18.x'
      - name: Install Dependencies
        run: npm install
      - name: Build the app artifact for prod
        run: npm run build --prod
      - name: Install Firetools
        run: npm install -g firebase-tools
      - name: Deploy angular app to Firebase
        run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
#        uses: w9jds/firebase-action@master
#        with:
#          args: deploy --only hosting
#        env:
#          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
