name: CI-develop

on:
  push:
    branches:
      - deploy-git-action

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: '18.13.0'
      - name: Install Dependencies
        run: npm install
      - name: Build the app artifact for prod
        run: npm run build --prod
      - name: Deploy angular app to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
